# Generated by Django 3.2.4 on 2021-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('mobile', models.IntegerField(default='', max_length=15)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
