# Generated by Django 3.2.4 on 2021-06-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='counter',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='shop.product'),
        ),
    ]
